{% set name = "importscan" %}
{% set version = "0.2" %}
{% set sha256 = "4fb19627e1349dfd7d49d9bbd1b1bfff0f0a13e884d6cf9dcaf16f865375c9b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
    - setuptools

  run:
    - python >=3.4

test:
  imports:
    - importscan

about:
  home: http://importscan.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Recursively import modules and sub-packages'
  description: |
    importscan provides a scan function that lets you recursively import a package and its sub-modules and sub-packages.
  doc_url: http://importscan.readthedocs.org/
  dev_url: https://github.com/faassen/importscan

extra:
  recipe-maintainers:
    - stuertz
