travis:
  secure:
    BINSTAR_TOKEN: KTbnM1qu0ATc7gNt4HJs/u8BYrAVpUnmbQg4K7urmIbPNazzgzzMAwwcLsuLmacYoSIA0kBMPckDTthMzHqwCFuz2YMtDgSgXAq9Co62bUtF0qcRl6GvaN6DXQ/Hye1l5M8KR8OigVqKoW+HGDelyHB1rn6uMaZ+BKAtPAXbJlYKdLL5Ff1KMbYNqYI5fXhc1jaTNpIpw/Azjxpm3I+DDKpLlXf9BdSEq3t/cUYaetMxgaykG52t+Vi8ynaL3uIWq1pGQ6XSIbURasA+UJRFQjz16Qn2x83jD2R9T/AVrIiOdScQxYriv+oEq1dZy63ONT03oB49lPe70qPVNBE7jQwBfyzHtcV8KCi75p4Qjmd3os61TdubQYXjXSK35Zguy0wUb0IuXR/ZCkGONTzzvMUos1hR4uJ6iqQO15pBCWtYL741i2oZUOnDdN/5/eK3RTlsY56vUVSuJV+SY598T6C7BjqSyPEzFOtPHCYn/0WFWB42h8KiPZOQQiLY4dE9p5stfqIYmLULVMBNfIuEYlWh6E/PrRxsB58gI7yvKhd5tsLZctSrxP0dTKEuWMXmpXgolzt/b+48sv3sHiYCKvx9jbLN43lcMTmM3PKjp7h3CcSoZ2+4cQFKQFsobhmkB7WmWayPvlolcJHVbEbH+tbCzc9fXlkYnDWvNWyVl30=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
